### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by camd**
Carl,

Here is the source with the GPL license added.  Please run your tests before checking in the merge.  Thanks.
-Cam

### CODE REVIEW

**Comment by carljm** [comment]
This isn't quite ready. Some notes:
1. There are some files here that are bundled and redistributed in accordance with their existing license terms, but were not created as part of this project, thus neither Mozilla nor uTest hold copyright, thus we can't grant license under the GPL. Specifically, all the files under static/fonts should be excluded, and in static/js the following files should be excluded: ICanHaz.js, elem-details.js, jquery-1.6.4.js, jquery.ba-dotimeout.js, jquery.ellipsis.js, jquery.form.js, jquery.mockjax.js, jquery.placeholder.js, jquery.slideshow.js, jquery.sorter.js, jquery.superformset.js, and modernizr.js.
2. For the Django HTML templates under "templates/", we should use Django comment syntax rather than HTML comment syntax. Since many of these files are includes that might appear in a page tens or even hundreds of times, having the license terms in each template file as an HTML comment will massively balloon the size of our HTML responses. To use Django block comment syntax, begin the block with "{% comment %}" and end it with "{% endcomment %}".
3. Similarly, for the JavaScript Mustache templating language templates under "jstemplates/", we should use the Mustache comment syntax, which begins with {{! and ends with }} (and can contain newlines).
4. For the Python files, I would prefer that the license terms be added as comment (each line beginning with #) rather than as docstring. Module docstrings can be accessed from the interactive Python prompt by someone playing around with the code, and are a form of documentation; having every docstring be a license block makes them not very usable in that way. Also, some of these files already have module docstrings; adding another one causes the original one to no longer be accessible as a docstring at all.

**Comment by carljm** [comment]
Also, robots.txt should not have the header added (it'll break it), and if manage.py has the header added, it needs to go below the "!#/usr/bin/env python" line, or else it'll break running "./manage.py".

**Comment by camd** [comment]
Sounds like I used my script with WAY too large a brush.  Which ended up being very sloppy of me.  Apologies.  Let me start from scratch and take another swing at this.  Thanks for the detailed response.

**Comment by carljm** [comment]
Oh, no worries! Not sloppy at all, perfectly reasonable for a first (and automated) pass. Hopefully tweaking the script and taking a second run at it won't be too time-consuming.

**Pull request closed without merging**
